5.1:
- './*'
Crypsis:
- './src/components/com_kunena/template/crypsis/*'
backend:
- './src/administrator/components/com_kunena/*'
Codeception tests:
- './tests/*'
- './codeception.yml'
documentation:
- './docs/*'
