kind: pipeline
name: default

clone:
  depth: 42

steps:
  - name: composer
    image: joomlaprojects/docker-tools:develop
    commands:
      - composer validate --no-check-all --strict
      - composer install --no-progress --no-suggest
  - name: git clone
    image: docker:git
    commands:
      - git clone https://github.com/Kunena/Codestyle.git ./codestyle
      - rsync -r ./codestyle/Kunena ./vendor/squizlabs/php_codesniffer/src/Standards
  - name: phpcs
    image: joomlaprojects/docker-images:php7.2
    commands:
      - echo $(date)
      - ./vendor/bin/phpcs --extensions=php -p --standard=Kunena ./src
      - echo $(date)
