kind: pipeline
name: default

clone:
  depth: 42

steps:
  - name: composer
    image: joomlaprojects/docker-tools:develop
    commands:
      - composer validate --no-check-all --strict
      - composer install --no-progress --no-suggest
  - name: npm
    image: node:11
    commands:
      - npm install selenium-standalone
  - name: phpcs
    image: joomlaprojects/docker-images:php7.2
    commands:
      - echo $(date)
      - ./vendor/bin/phpcs --config-set ignore_warnings_on_exit 1
      - ./vendor/bin/phpcs --config-set ignore_errors_on_exit 1
      - ./vendor/bin/phpcs --extensions=php -p --standard=./vendor/kunena/codestyle/Kunena ./src
      - echo $(date)
