dist: xenial
services:
  - mysql
language: php
php:
  - "7.2"
  - "7.3"
addons:
  chrome: "stable"
before_install:
  - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS test_joomla;'
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('joomla_ut') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -pjoomla_ut
  - sudo service mysql restart
script:
  # Build
  - composer install
  - vendor/bin/phing -f build/phing/build.xml
  - git clone https://github.com/joomla/joomla-cms.git ./tests/test-install
  - cd tests/test-install
  - git checkout 4.0-dev
  - composer install
  - npm install
  - ./node_modules/.bin/selenium-standalone install
  - cd ../
  - mv ./acceptance.suite.yml ./test-install/tests/Codeception/acceptance.suite.yml
  - cd test-install
  - ./node_modules/.bin/selenium-standalone start
  - ./libraries/vendor/bin/codecept run acceptance ./tests/Codeception/acceptance/install
  - ./libraries/vendor/bin/codecept run acceptance ./tests/Codeception/acceptance/install/kunenaCest
