language: php
php:
- "7.2"
- "7.3"
addons:
  chrome: "stable"
  sonarcloud:
      organization: "kunena-forum"
      token:
        secure: "5236152baa004029e309405ee0af8e30ac1add88"
      branches:
        - "K6.0"
jdk:
  - oraclejdk12
script:
  # Build
  - composer install
  - vendor/bin/phing -f build/phing/build.xml
  - git clone https://github.com/joomla/joomla-cms.git ./tests/test-install
  - cd tests/test-install
  - git checkout 4.0-dev
  - composer install
  # Bug joomla
  - cd ../
  - mv ./package.json ./test-install/package.json
  - mv ./package-lock.json ./test-install/package-lock.json
  - cd test-install
  - npm install
  - ./node_modules/.bin/selenium-standalone install
  - ./node_modules/.bin/selenium-standalone start
  - cd ../
  - mv ./acceptance.suite.yml ./test-install/tests/Codeception/acceptance.suite.yml
  - ./libraries/vendor/bin/codecept run acceptance ./tests/Codeception/acceptance/install
  - ./libraries/vendor/bin/codecept run acceptance ./tests/Codeception/acceptance/install/kunenaCest
  #- sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'
