language: php
php:
- "7.2"
- "7.3"
addons:
  chrome: "stable"
  sonarcloud:
      organization: "kunena-forum"
      token:
        secure: "5236152baa004029e309405ee0af8e30ac1add88"
      branches:
        - "K6.0"
jdk:
  - oraclejdk12
script:
  # Build
  - composer install
  - vendor/bin/phing -f build/phing/build.xml
  - git clone https://github.com/joomla/joomla-cms.git ./tests/test-install
  - cd tests/joomla
  - git checkout 4.0-dev
  - composer install
  - npm install
  - ./node_modules/.bin/selenium-standalone install
  - ./node_modules/.bin/selenium-standalone start
  - libraries/vendor/bin/codecept run acceptance tests/Codeception/acceptance/install
  - libraries/vendor/bin/codecept run acceptance tests/Codeception/acceptance/install/kunenaCest
  - mv tests/acceptance.suite.yml tests\joomla\tests\Codeception\acceptance.suite.yml
  # Disable tests for now vendor/bin/robo run:tests --use-htaccess
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'
