name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Start CI Tests
      run: echo Tests started for Kunena Forum
    - name: Composer
      run: |
          composer validate --no-check-all --strict
          composer install --no-progress --no-suggest
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: npm install, build and test
      run: |
        npm install npm@latest -g
        npm install
    - name: Run Codestyle
      using: docker
      image: joomlaprojects/docker-images:systemtests
      run: |
        ./vendor/bin/phpcs --extensions=php -p --standard=./vendor/kunena/codestyle/Kunena ./src
