name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Start CI Tests
      run: echo Tests started for Kunena Forum
    - name: Composer install
      run: |
        echo Installing composer
        composer validate --no-check-all --strict
        composer install --no-progress --no-suggest
    - name: Codestyle check
      run: |
        echo running codestyle check
        ./vendor/bin/phpcs --config-set ignore_errors_on_exit 1
        ./vendor/bin/phpcs --config-set ignore_warnings_on_exit 1
        ./vendor/bin/phpcs --extensions=php -p --standard=./vendor/kunena/codestyle/Kunena ./src
    - uses: actions/setup-node@v1
      with:
          node-version: '10.x'
    - name: npm install
      run: |
        export DISPLAY=':99.0'
        /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        npm install npm@latest -g
        npm install selenium-standalone
    - name: Docker
      run: |
        docker build -t www:joomla .
        docker run -d www:joomla
    - name: Install Joomla
      run: |
        mkdir -p ./tests/www
        cd ./tests/www
        git clone -b 4.0-dev https://github.com/joomla/joomla-cms.git .
        composer install
        npm install
        cd ../../
        ls ./tests/www
        ping http://localhost
        ping http://localhost/tests
        ping http://localhost/tests/www
        ping http://localhost/tests/joomla-cms
        ping http://localhost/tests/joomla
      continue-on-error: true
    - name: Codeception
      run: |
        bash ./tests/Codeception/drone-system-run.sh
