name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: joomlaprojects/docker-images:systemtests
      env:
        NODE_ENV: development
    steps:
    - uses: actions/checkout@v1
    - name: Start CI Tests
      run: echo Tests started for Kunena Forum
    - name: Composer & Npm Install
      run: |
       composer validate --no-check-all --strict
       composer install --no-progress --no-suggest
       npm install selenium-standalone

  cs:
    runs-on: ubuntu-latest
    container:
      image: joomlaprojects/docker-images:systemtests
      env:
        NODE_ENV: development
    steps:
      - name: Start CI Tests
        run: echo Install composer & codestyle check
      - name: phpcs v3
        run: |
          composer validate --no-check-all --strict
          composer install --no-progress --no-suggest
          ./vendor/bin/phpcs --extensions=php -p --standard=./vendor/kunena/codestyle/Kunena ./src
