name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [11, 12]
    container:
      image: joomlaprojects/docker-images:systemtests
      env:
        NODE_ENV: development
    steps:
    - uses: actions/checkout@v1
    - name: Start CI Tests
      run: echo Tests started for Kunena Forum
    - name: Composer
      run: |
          composer validate --no-check-all --strict
          composer install --no-progress --no-suggest
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        version: 11
    - name: npm install, build and test
      run: |
        npm install

  cs:
    runs-on: ubuntu-latest
    container:
      image: joomlaprojects/docker-images:systemtests
      env:
        NODE_ENV: development
    steps:
      - name: Start CI Tests
        run: echo Install composer & codestyle check
      - name: phpcs v3
        run: |
          composer validate --no-check-all --strict
          composer install --no-progress --no-suggest
          ./vendor/bin/phpcs --extensions=php -p --standard=./vendor/kunena/codestyle/Kunena ./src
